id: AEFE8D02F
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö and Khandro Tsering
  Chödrön
type: translation
pechas:
- IDC14DE66
- I3528B1BE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:27.416331
  last_modified_at: 2023-01-04 12:48:27.416348
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  IDC14DE66/F2F7: E1AA
  I3528B1BE/0D34: E1AA
